# About Julia

Before hopping into some numerical methods and running benchmarks, I thought it would be smart to show off some functionality of Julia so that people can see why (in my humble opinion) Julia is a far superior programming language to MATLAB. 

First off, Julia as INCREDIBLY similar syntax to MATLAB. If statements, for loops, functions, creating a matrix, etc. are all the same in MATLAB as they are in Julia. For example, here is an example of a `for` loop in Julia:

In [3]:
for i in 1:10
    println(i)
end

1
2
3
4
5
6
7
8
9
10


In [4]:
A = zeros(2, 2)

2×2 Matrix{Float64}:
 0.0  0.0
 0.0  0.0

In [5]:
B = ones(3, 4)

3×4 Matrix{Float64}:
 1.0  1.0  1.0  1.0
 1.0  1.0  1.0  1.0
 1.0  1.0  1.0  1.0

In [6]:
v = rand(2)

2-element Vector{Float64}:
 0.6248419113729959
 0.1012259094580078

Julia also supports **broadcasting** (or element-wise operations) in the same way that MATLAB does. So we can multiply every element in `v` by 5 super easily:

In [11]:
v .* 5

2-element Vector{Float64}:
 3.1242095568649795
 0.506129547290039

Julia also uses 1-based indexing (unlike C, Java, Python, etc.) which is additionally similar to MATLAB. However, there are some notable differences that need to be made between MATLAB and Julia. You can read up on all these differences [here](https://docs.julialang.org/en/v1/manual/noteworthy-differences/), but I am going to list the bigger ones here.

For starters, *indexing is done with square brackets and not parentheses*. So to access an element in `A`, we would need to write:

In [13]:
A[1, 2]

0.0

Another really important difference is that *arrays are not copied when assigned to another variable.* For example, if we wanted to create a new matrix `B` in MATLAB, `B=A` will create that new matrix with the same values as `A`, but changing values in `B` will not change values in `A`. This is NOT the case in Julia, as illustrated below:

In [15]:
B = A
B[1, 1] = 1
A

2×2 Matrix{Float64}:
 1.0  0.0
 0.0  0.0

See? We printed the values of `A` and the first element was still changed. If you want to truly make copies of variables, you will have to use the `copy()` function:

In [17]:
A = zeros(2, 2)
B = copy(A)
B[1, 1] = 1
A

2×2 Matrix{Float64}:
 0.0  0.0
 0.0  0.0

The imaginary unit is called `im` in Julia, rather than `i` or `j`. I am in favor of this change because it lets us use `i` and `j` as incrementing variables in our `for` loops now if we want.

*Julia does not dynamically resize arrays*. As an example:

In [24]:
v = rand(3)
v[4] = 2

BoundsError: BoundsError: attempt to access 3-element Vector{Float64} at index [4]

If you want to add values to an array, you have to use actual function calls like `push!` and `append!`. This is actually much more efficient than the MATLAB equivalent `v(end+1) = 2`.

In [25]:
push!(v, 2)

4-element Vector{Float64}:
 0.4711367009253731
 0.1420263964424301
 0.9826961911831995
 2.0

Finally, *Julia functions return values from their last expression or whatever is listed after the `return` keyword.* This means that you do NOT have to list what specifically will be returned in your function declarations. As someone who writes software in other programming languages, this was my biggest frustration with MATLAB. Additionally, returning multiple values in Julia will result in all the values coming back bundled inside of a tuple.

In [27]:
function add_subtract_multiply(a, b)
    c = a + b
    d = a - b
    e = a * b

    return c, d, e
end

add_subtract_multiply(2, 5)

(7, -3, 10)

Finally, the major feature of Julia that I am absolutely in love with - and the feature that I believe makes learning Numerical Methods much easier than in MATLAB:

**Julia lets you insert LaTeX symbols into your code.**

This is truly beautiful. You can now read and write code truly mathematically. It's a phenomenally powerful feature that I absolutely adore. I find that my code in turn becomes more readable because I can assign the actual symbol a value rather than coming up with some obscure variable name.

To add a LaTeX symbol into your code, type `\` and the name of the character that you want, then hit tab. The symbol will be automatically inserted into your code.

For example, here is me assigning a value to a LaTeX variable:

In [28]:
λ = 4
λ

4

Not only can I use LaTeX for variable names, but Julia also understands LaTeX symbols from within code. For example:

In [31]:
for i ∈ 1:10
    println(i)
end

1
2
3
4
5
6
7
8
9
10


I seriously cannot stress how much I adore this feature of Julia. For that reason alone, I think every mathematician should be coding in Julia. Granted, there are other incredible performance features that we will see in the coming chapters, but this is definitely a nice start! 

Now that we know some key features of Julia (and some key differences that it has from MATLAB), we can start talking about some numerical methods!